

# SCROLL PROCESSOR
jcs.total.height:
  "return Math.max(document.body.scrollHeight, document.body.offsetHeight, document.documentElement.clientHeight, document.documentElement.scrollHeight, document.documentElement.offsetHeight);"
jcs.scroll.top:
  'top.window.scroll(0, 0)'
jcs.scroll.down:
  'window.scrollBy(0, {});'
jcs.scroll.max.number:
  10


# HUNPY LOG
log.name:
  'hunpy'
log.dir:
  '/home/sisco/PycharmProjects/hunpy/log'
log.string.format:
  '%(asctime)s - %(levelname)s - %(message)s'
log.date.format:
  '%Y-%m-%d_%H:%M:%S'


# DATABASE CONNECTION
connection.parameters:
  'user': 'root'
  'password': 'pupahit66'
  'host': 'localhost'
  'database': 'hunpy'

# DATASOURCE PATHS
datasource.relative.paths:
  adservers:            /home/sisco/PycharmProjects/hunpy/datasource/adservers.txt
  ignore.domain:        /home/sisco/PycharmProjects/hunpy/datasource/ignore_domain.txt
  ignore.path:          /home/sisco/PycharmProjects/hunpy/datasource/ignore_path.txt


# FORMATS
format.datetime:
  - '%Y-%m-%d %H:%M:%S'

# MAXIMUM STRING CHARACTERS
max.source.len: 512
max.landing.len: 512

# MINIMUM AD SIZE
advert.min_pixels:     400
advert.min_dimension:  10

# REQUESTS (utils_requests)
http_bad_request:
  - 0
  - 204
  - 400
  - 401
  - 403
  - 404
  - 500


# DRIVER OPTIONS
page.load.timeout:
  30
chrome.user.agent:
  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64_59.0.3071.86 Safari/537.36
chrome.window.width:
  1440
chrome.window.height:
  990
chrome.option.profile.path:
  --user-data-dir=/home/sisco/PycharmProjects/hunpy/profile
chrome.option.dns.prefetch.disable:
  --dns-prefetch-disable
chrome.option.ignore.ssl.errors:
  --ignore-ssl-errors=true
chrome.option.disable.infobars:
  --disable-infobars
chrome.option.disable.gpu:
  --disable-gpu
chrome.option.disable-plugins:
  --disable-plugins
chrome.option.nosandbox:
  --no-sandbox
chrome.option.disable.crashed.bubble:
  --disable-session-crashed-bubble
chrome.option.headless:
  --headless
chrome.option.disable.notifications:
  --disable-notifications
chrome.chromedriver.log:
  --log-path=/home/sisco/PycharmProjects/hunpy/chromedriver.log


# XPATH
x.body:           .//body
x.iframe:         .//iframe
x.iframe_n:       .//iframe[{}]
x.equals:         '@{}="{}"'
x.contains:       contains(@{}, "{}")
x.and:            ' and '
x.img:            .//img
x.a_img:          .//a//img
x_aimg:           .//a/img
x.ancestor_a:     ./ancestor::a

# IFRAME ATTRIBUTES
txt.html:    html
txt.id:      id
txt.name:    name
txt.src:     src
txt.title:   title
txt.style:   style
txt.href:    href
txt.onclick: onclick


src.ignored.subdomains:
  - safeframe
  - cache
  - templates
  - addons
  - uploads
  - wp-content
  - plugins

src.ignore.landing:
   - 'about:'
   - 'about:blank'
   - javascript
   - widget
















