
# PROCESSOR MODULES
processors:
  - scroll_processor
  - image_processor
  - iframe_processor
  - storage_processor

# SCROLL PROCESSOR
js.total.height:
  "return Math.max(document.body.scrollHeight, document.body.offsetHeight, document.documentElement.clientHeight, document.documentElement.scrollHeight, document.documentElement.offsetHeight);"
js.scroll.top:
  'top.window.scroll(0, 0)'
js.scroll.down:
  'window.scrollBy(0, {});'
js.scroll.max.number:
  6
js.time.wait.scroll:
  0.5

# HUNPY LOG
log.name:
  'hunpy'
log.dir:
  'logs'
log.string.format:
  '%(asctime)s - %(levelname)s - %(message)s'
log.date.format:
  '%Y-%m-%d_%H:%M:%S'


# DATABASE CONNECTION
connection.parameters:
  'user': 'root'
  'password': 'pass123'
  'host': 'localhost'
  'database': 'hunpy'

# DATASOURCE RELATIVE PATHS
datasource.relative.paths:
  sources: datasource/sources.txt
  adservers: datasource/adservers.txt
  ignore.domain: datasource/ignore_domain.txt
  ignore.path: datasource/ignore_path.txt

# FORMATS
format.datetime:
  - '%Y-%m-%d %H:%M:%S'

# MAXIMUM STRING CHARACTERS
max.source.len: 512
max.landing.len: 512

# MINIMUM AD SIZE
advert.min_pixels:     400
advert.min_dimension:  10

# REQUESTS (utils_requests)
http_bad_request:
  - 0
  - 204
  - 400
  - 401
  - 403
  - 404
  - 500

headers:
  user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36

# DRIVER OPTIONS
page.load.timeout:
  30
chrome.user.agent:
  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36
chrome.window.width:
  1440
chrome.window.height:
  990
chrome.option.profile.path:
  profile
chrome.option.dns.prefetch.disable:
  --dns-prefetch-disable
chrome.option.ignore.ssl.errors:
  --ignore-ssl-errors=true
chrome.option.disable.infobars:
  --disable-infobars
chrome.option.disable.gpu:
  --disable-gpu
chrome.option.disable-plugins:
  --disable-plugins
chrome.option.nosandbox:
  --no-sandbox
chrome.option.disable.crashed.bubble:
  --disable-session-crashed-bubble
chrome.option.headless:
  --headless
chrome.option.disable.notifications:
  --disable-notifications
chrome.chromedriver.log:
  --log-path=hunpy/chromedriver.log
chrome.binary.location:
  /usr/bin/chromium-browser


# XPATH
x.body:           .//body
x.iframe:         .//iframe
x.iframe_n:       .//iframe[{}]
x.equals:         '@{}="{}"'
x.contains:       contains(@{}, "{}")
x.and:            ' and '
x.img:            .//img
x.a_img:          .//a//img
x_aimg:           .//a/img
x.ancestor_a:     ./ancestor::a

# Iframe attributes
txt.html:    html
txt.id:      id
txt.name:    name
txt.src:     src
txt.title:   title
txt.style:   style
txt.href:    href
txt.onclick: onclick

src.ignore.path.domain.exceptions:
  - ds.serving-sys.com
  - secure-ds.serving-sys.com
  - cdn.flashtalking.com'

src.ignore.iframe:
  - javascript:false
  - about:blank
  - javascript:'';

src.ignore.landing:
   - 'about:'
   - 'about:blank'
   - javascript
   - widget










