


# LOG
log.name:
  'hunpy'
log.dir:
  '/home/sisco/PycharmProjects/hunpy/log'
log.string.format:
  '%(asctime)s - %(levelname)s - %(message)s'
log.date.format:
  '%Y-%m-%d_%H:%M:%S'


# DATABASE CONNECTION
connection.parameters:
  'user': 'root'
  'password': 'pupahit66'
  'host': 'localhost'
  'database': 'hunpy'


datasource.relative.paths:
  adservers:            /home/sisco/PycharmProjects/hunpy/datasource/adservers.txt
  ignore.domain.path:   /home/sisco/PycharmProjects/hunpy/datasource/ignore_domain_path.txt
  ignore.domain:        /home/sisco/PycharmProjects/hunpy/datasource/ignore_domain.txt
  ignore.path:          /home/sisco/PycharmProjects/hunpy/datasource/ignore_path.txt


format.datetime:
  - '%Y-%m-%d %H:%M:%S'

# MAXIMUM STRING CHARACTERS
max.source.len: 512
max.landing.len: 512

# MINIMUM AD SIZE
advert.min_pixels:     400
advert.min_dimension:  10

# REQUESTS (utils_requests)
http_bad_request:
  - 0
  - 204
  - 400
  - 401
  - 403
  - 404
  - 500

# DRIVER OPTIONS
chrome.options:
   - --dns-prefetch-disable
   - --disable-gpu
   - --disable-plugins
   - --no-sandbox
   - --disable-infobars
   - --disable-session-crashed-bubble
   - --ignore-certificate-errors
   - --ignore-ssl-errors=true
chrome.headless_option:       --headless
chrome.size_option:           --window-size={},{}
chrome.user_data_dir:         --user-data-dir={}
chrome.user_agent:            --user-agent={}
chrome.chromedriver_log:      --log-path={}
chrome.chromedriver_log_name: chromedriver.log

# XPATH
x.body:           .//body
x.iframe:         .//iframe
x.iframe_n:       .//iframe[{}]
x.equals:         '@{}="{}"'
x.contains:       contains(@{}, "{}")
x.and:            ' and '
x.img:            .//img
x.a_img:          .//a//img
x_aimg:           .//a/img
x.ancestor_a:     ./ancestor::a

# IFRAME ATTRIBUTES
txt.html:    html
txt.id:      id
txt.name:    name
txt.src:     src
txt.title:   title
txt.style:   style
txt.href:    href
txt.onclick: onclick


src.ignored.subdomains:
  - safeframe
  - cache
  - templates
  - addons
  - uploads
  - wp-content
  - plugins

src.ignore.landing:
   - 'about:'
   - 'about:blank'
   - javascript
   - widget
















